"""empty message

Revision ID: 007f5ee2b397
Revises: a02cebffcf1b
Create Date: 2024-11-05 16:53:04.823149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007f5ee2b397'
down_revision = 'a02cebffcf1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
