"""empty message

Revision ID: 07d06f83e5d5
Revises: 1994ee6a3314
Create Date: 2024-11-10 01:06:18.521044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07d06f83e5d5'
down_revision = '1994ee6a3314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=50), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sizes', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('colors', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('colors')
        batch_op.drop_column('sizes')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_column('color')
        batch_op.drop_column('size')

    # ### end Alembic commands ###
