"""empty message

Revision ID: 1994ee6a3314
Revises: 776a5c3e1a78
Create Date: 2024-11-05 20:05:25.399452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1994ee6a3314'
down_revision = '776a5c3e1a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_factor_auth', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('data_sharing', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('email_notifications', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('sms_notifications', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('sms_notifications')
        batch_op.drop_column('email_notifications')
        batch_op.drop_column('data_sharing')
        batch_op.drop_column('two_factor_auth')

    # ### end Alembic commands ###
