"""Fix Admin and Activity models

Revision ID: 24604c73ec1f
Revises: 7e2c51aec477
Create Date: 2024-11-13 22:43:02.431051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24604c73ec1f'
down_revision = '7e2c51aec477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('activities_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'admins', ['admin_id'], ['admin_id'])
        batch_op.drop_column('admin_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('activities_ibfk_1', 'admins', ['admin_user_id'], ['admin_id'])
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###
