"""empty message

Revision ID: 3215ae1881d0
Revises: 23c95f18d152
Create Date: 2024-11-18 17:47:02.654844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3215ae1881d0'
down_revision = '23c95f18d152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', mysql.TEXT(), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
