"""New changes added

Revision ID: 4bfc075b79d4
Revises: f6f9354ebda5
Create Date: 2024-11-22 20:17:51.377741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4bfc075b79d4'
down_revision = 'f6f9354ebda5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('admin_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('admin_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
